esphome:
  name: dht-climate-sensor
  friendly_name: dht-climate-sensor

substitutions:
  # Modify variables based on your settings
  devicename: dht-climate-sensor

esp8266:
  board: nodemcuv2

# Enable logging
logger:

#Enable Home Assistant API
api:
  encryption:
    key: !secret ha_api_key

ota:
  - platform: esphome
    password: !secret ota_password

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password

captive_portal:

# MQTT Configuration
mqtt:
  broker: !secret mqtt_broker
  username: !secret mqtt_username
  password: !secret mqtt_password
  discovery: true
  discovery_retain: true
  birth_message:
    topic: ${devicename}/status
    payload: online
    retain: true
  will_message:
    topic: ${devicename}/status
    payload: offline
    retain: true

  
switch:
  # The following can be omitted
  - platform: restart
    name: ${devicename} restart

sensor:
  - platform: wifi_signal
    name: ${devicename} wifi signal
    update_interval: 60s
    filters:
      - delta: 2.0  # Only send if WiFi signal changes by 2 dBm or more
  - platform: dht
    pin:
      number: GPIO14
      mode:
        input: true
        pullup: true
    temperature:
      name: " $devicename Temp"
      filters:
        - delta: 0.1  # Only send if temperature changes by 0.1°C or more
    humidity:
      accuracy_decimals: 1
      name: " $devicename Humidity"
      filters:
        - delta: 0.5  # Only send if humidity changes by 0.5% or more
    update_interval: 5s

  # human readable uptime sensor output to the text sensor above
  - platform: uptime
    name: ${devicename} Uptime in Days
    id: uptime_sensor_days
    update_interval: 60s
    on_raw_value:
      then:
        - text_sensor.template.publish:
            id: uptime_human
            state: !lambda |-
              int seconds = round(id(uptime_sensor_days).raw_state);
              int days = seconds / (24 * 3600);
              seconds = seconds % (24 * 3600);
              int hours = seconds / 3600;
              seconds = seconds % 3600;
              int minutes = seconds /  60;
              seconds = seconds % 60;
              return (
                (days ? String(days) + "d " : "") +
                (hours ? String(hours) + "h " : "") +
                (minutes ? String(minutes) + "m " : "") +
                (String(seconds) + "s")
              ).c_str();

time:
  - platform: sntp
    id: homeassistant_time
    timezone: "Asia/Kolkata"  # Change to your timezone
    servers:
      - "ssinghhac.duckdns.org"  # Your Home Assistant server with Chrony
      - "pool.ntp.org"         # Fallback server
    update_interval: 15min

# Text sensors with general information.
text_sensor:
  # Expose ESPHome version as sensor.
  - platform: version
    name: $devicename Version
  # Expose WiFi information as sensors.
  - platform: wifi_info
    ip_address:
      name: $devicename IP
    bssid:
      name: $devicename BSSID

  # human readable update text sensor from sensor:uptime
  - platform: template
    name: Uptime Human Readable
    id: uptime_human
    icon: mdi:clock-start
    
